### ISSUE TITLE
获取被引数时，不要更新元数据/Donot update metadata while fetching citation counts

### ISSUE THREAD

**Issue by zhikaiyici** [fkguo/zotero-inspire#7]
从INSPIRE获取被引数时，条目元数据被更新，即使勾选了`Citation counts only`。导致预印本被错误更新为期刊文章。
Item metadata is updated while fetching citation counts from INSPIRE even with `Citation counts only`  checked. `Preprint` is wrongly updated to `Journal Article`.

**Comment by fkguo** [comment]
The change of item type `Preprint` to `Journal Article` even if the item has not yet been published in a journal is done on purpose. The arXiv number is set to `journalAbbr` for preprint papers so that it can appear in the Journal Abbr column of the main window.

**Comment by crnkv** [comment]
@fkguo 我也遇到了这个问题，请问能不能加一个选项（哪怕只隐藏在高级设置 `about:config` 里也好）让用户选择是否自动修改 itemType 到 journalArticle ？
因为我的 library 按照 Zotero 官方建议，将 item 区分成 journalArticle, Preprint, conferencePaper, Book （主要常用这四类），而 inspire 返回的格式全部都是 article 是不区分的，我想保留我自己 library 里的区分（将 arXiv 号存在 Extra 里）

I encountered the same issue. May I ask if it's possible to let users choose whether to automatically change itemType to journalArticle? (A variable hidden in the Advanced Preferences `about:config` for example)
That's because I follow Zotero's official advice and categorize items into journalArticle, Preprint, conferencePaper and Book (mainly), while inspire only returns metadata with 'article' type with no differentiation. I personally wish to preserve the Zotero way of management. (arXiv numbers stored in the Extra field)

**Comment by salsergey** [comment]
Changing the type of the items seems very strange to me. It's the main reason not to use this extension at all, since I want my preprints to be marked as preprints. Citation style for preprints is usually different from that for journal papers.

**Comment by fkguo** [comment]
> Changing the type of the items seems very strange to me. It's the main reason not to use this extension at all, since I want my preprints to be marked as preprints. Citation style for preprints is usually different from that for journal papers.

Indeed that was designed in purpose before for old zotero versions.
Now I have added one preference setting in the new version, default to keep preprint item type for unpublished papers.

**Comment by salsergey** [comment]
Thank you! Now I'll give it a try.
